# Generated by Django 4.2.1 on 2023-05-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
